# Generated by Django 5.1.2 on 2024-11-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='chatbot_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
