# Generated by Django 5.1.2 on 2024-10-24 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0003_chatbot_embed_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('history', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chatbots.chatbot')),
            ],
            options={
                'db_table': 'chatbot_users',
            },
        ),
    ]
