# Generated by Django 5.1.2 on 2024-10-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0004_chatbotuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='color',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='chatbot_border_radius',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='font_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='primary_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='widget_border_radius',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='widget_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
