# Generated by Django 5.1.2 on 2024-11-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0005_remove_chatbot_color_chatbot_chatbot_border_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='status',
            field=models.CharField(choices=[('training', 'Training'), ('live', 'Live'), ('failed', 'Failed')], default='training', max_length=20),
        ),
    ]
