version: '3.8'

services:
  web:
    build: .
    command: uvicorn backend.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  celery:
    build: .
    command: celery -A backend worker --loglevel=debug
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
