# Generated by Django 5.1.2 on 2024-10-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
    ]
