# Generated by Django 5.1.2 on 2024-12-19 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_num_chatbots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('max_chatbots', models.IntegerField(blank=True, null=True)),
                ('max_pdfs', models.IntegerField(blank=True, null=True)),
                ('max_pages_per_pdf', models.IntegerField(blank=True, null=True)),
                ('max_url_links', models.IntegerField(blank=True, null=True)),
                ('max_prompts_per_day', models.IntegerField(blank=True, null=True)),
                ('max_retrains_per_month', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_status', models.CharField(blank=True, max_length=50, null=True)),
                ('subscription_start_date', models.DateTimeField(auto_now_add=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptions')),
            ],
            options={
                'db_table': 'organization_subscription',
            },
        ),
    ]
