# Generated by Django 5.1.2 on 2024-12-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
