# Generated by Django 5.1.2 on 2024-12-03 07:15

import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for row in User.objects.all():
        row.new_id = uuid.uuid4()
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        
        migrations.RunPython(gen_uuid),
        
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        
        migrations.RenameField(
            model_name='user',
            old_name='new_id',
            new_name='id',
        ),
        
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False),
        ),
    ]
