# Generated by Django 5.1.2 on 2024-12-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teaminvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvite',
            name='accepted_invite',
            field=models.BooleanField(default=False),
        ),
    ]
