# Generated by Django 5.1.2 on 2024-12-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_needs_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_invite',
            field=models.BooleanField(default=False),
        ),
    ]
