# Generated by Django 5.1.2 on 2024-12-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_invite_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamInvite',
        ),
    ]
